name: Homebrew

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  homebrew:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get latest tag
        id: tag
        run: |
          git fetch --tags
          TAG=$(git describe --tags --abbrev=0)
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          formula: syswatch
          repoowner: joaaomanooel
          reponame: homebrew-syswatch
          version: ${{ steps.tag.outputs.tag }}
